export const header: string;
export const serverlHeader: string;
export const sectionHeader: string;
export const channelTitle: string;
export const toolbar: string;
export const searchInput: string;
export const menuBtn: string;
export const menuExitBtn: string;
export const popoverTitle: string;